# Generated by Django 4.2.30 on 2026-04-21 07:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tools.path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_code', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='category/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=500, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='Meta Keywords')),
                ('product_count', models.PositiveBigIntegerField(default=0, verbose_name='Count the products')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default='2.00', max_digits=10, verbose_name='Import prcie')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Code SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='Barcode')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='Low inventory alert threshold')),
                ('track_stock', models.BooleanField(default=True, verbose_name='Inventory tracking')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Product is featered')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Product is bestseller')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Demensions (width x hight x high)')),
                ('color', models.CharField(choices=[('BLACK', 'Black'), ('GOLD', 'Gold'), ('RED', 'Red')], default='BLACK', max_length=20)),
                ('material', models.CharField(blank=True, max_length=50, verbose_name='Material')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=500, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='Meta Keywords')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Wiewed')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='Đã bán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date publish')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Date update')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='store.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tools.path.get_upload_path)),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'ProductImage',
                'verbose_name_plural': 'Images of Product',
                'ordering': ['order'],
                'unique_together': {('product', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'is_active'], name='store_produ_name_e8f8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='store_produ_categor_591340_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'is_active'], name='store_categ_name_d71082_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='store_categ_parent__fac0c6_idx'),
        ),
    ]
