# Generated by Django 5.2.7 on 2026-04-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_parent_alter_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Barcode'),
        ),
    ]
